# fly.toml app configuration file generated for personal-page on 2023-08-14T23:35:10-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "personal-page"
primary_region = "gig"
console_command = "/rails/bin/rails console"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
